version: '3.1'

services:
  fiaprestaurant-service-db:
    container_name: postgresql-fiaprestaurant
    image: postgres:15.1
    environment:
      POSTGRES_DB: fiaprestaurant-db
      POSTGRES_USER: fiaprestaurant-postgres-user
      POSTGRES_PASSWORD: fiaprestaurant-postgres-pwd
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgres
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge